// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsg6FgeC2t0Ed0Xndo0kydgQAZP6wfqLA',
    appId: '1:888835336171:web:4dd866314e221a3a2c1bae',
    messagingSenderId: '888835336171',
    projectId: 'chat-app-e99f0',
    authDomain: 'chat-app-e99f0.firebaseapp.com',
    storageBucket: 'chat-app-e99f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv8wAzZtg5En7L6pJ3kgtaYa49W4dP8oM',
    appId: '1:888835336171:android:bd23fe9995cb7dcb2c1bae',
    messagingSenderId: '888835336171',
    projectId: 'chat-app-e99f0',
    storageBucket: 'chat-app-e99f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfuqjXRskrdHseZHrvns-Wlm8tLC5X1rA',
    appId: '1:888835336171:ios:048c54f130f9ff112c1bae',
    messagingSenderId: '888835336171',
    projectId: 'chat-app-e99f0',
    storageBucket: 'chat-app-e99f0.appspot.com',
    iosClientId: '888835336171-fhi3a0f7jtt0m7gh9arak64d6gcr92kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfuqjXRskrdHseZHrvns-Wlm8tLC5X1rA',
    appId: '1:888835336171:ios:048c54f130f9ff112c1bae',
    messagingSenderId: '888835336171',
    projectId: 'chat-app-e99f0',
    storageBucket: 'chat-app-e99f0.appspot.com',
    iosClientId: '888835336171-fhi3a0f7jtt0m7gh9arak64d6gcr92kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
